name: LoginSystem
version: '${project.version}'
main: pl.pomoku.loginsystem.LoginSystem
api-version: 1.19
authors: [ HubiRto ]
description: System logowania na serwer
commands:
  register:
  login:
  email:
  changepassword:
  logout:
  pomoc:
  remember:
